#!/bin/bash

chmod +x /opt/github.com/simon.services/hello-world/bin/hello-world
supervisorctl update helloworld
cp -fv /opt/github.com/simon.services/hello-world/consul.d/helloworld.json /opt/github.com/simon.services/consul/consul.d/

